### ISSUE TITLE
Immediate operands >127 not supported

### ISSUE THREAD

**Issue by tittoassini** [divipp/x86-64#6]
This fails:

mov al 128

with error:

pattern-test: immediate value of this size is not supported: (al,128)
CallStack (from HasCallStack):
  error, called at ./CodeGen/X86/CodeGen.hs:513:18 in x86-64bit-0.4.1-5g9gBLWiXoG1iUMmlHhuvp:CodeGen.X86.CodeGen

**Comment by tittoassini** [comment]
More precisely, this fails:

compile (mov al 128)

**Comment by divipp** [comment]
Thanks for the report I try to find a solution.

**Comment by divipp** [comment]
Until I implement a solution, the workaround is to use negative values: mov al (-128)

**Comment by divipp** [comment]
I fixed this particular case, please reopen the issue or open a new one if you find similar problems.

**Comment by tittoassini** [comment]
'mov' seems fine but other operations are still not working, these fails:

and_ al 200
xor_ al 200
and_ ax 20000
xor_ ax 20000

**Comment by divipp** [comment]
Thanks, I think I fixed all of these issues now. Please tell me if you find any regressions.

**Comment by tittoassini** [comment]
Now it all seems good :-)
